#!/usr/bin/env node
/**
 * render_email.mjs — render references/templates/sponsor-pitch.mjs to HTML and plain text.
 *
 *   node scripts/render_email.mjs [--dossier artifacts/dossier.json]
 *
 * Props come from the dossier and the festival packet. A prop with no evidence behind it
 * is omitted, and the template's own guard drops that section rather than rendering a gap.
 * Both outputs are written: some clients show the text part, and an autogenerated one
 * reads as broken.
 *
 * Two gates run before anything renders, and both refuse rather than warn.
 *
 * The compliance gate: a target the exclusion file blocked never reaches a draft. Bob's
 * own email flagged age and compliance limits on the cannabis names, and a drafted pitch
 * is one copy-paste away from a sent one.
 *
 * The evidence gate: the pitch opens on a dated activation. Without one there is nothing
 * true to say about why this company, now — and the alternative the model reaches for is
 * flattery, which is how a cold pitch identifies itself as automated in its first line.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};
const read = async (p) => JSON.parse(await readFile(resolve(p), "utf8"));

const dossier = await read(arg("dossier", "artifacts/dossier.json"));
const { campaignDir, sender } = await import("./campaign.mjs");
const festival = await read(arg("festival", `${campaignDir().dir}/festival-packet.json`));
const agencySender = sender();

// Campaign brand tokens: extracted once per campaign from the client's own deck.
// Missing tokens are generated on the spot so the first render is already branded;
// re-run `npm run brand` after a deck revision or to merge a site styleguide.
let brand = null;
if (!existsSync(resolve("artifacts/brand-tokens.json"))) {
  try {
    execFileSync("node", [resolve(import.meta.dirname, "extract_brand.mjs")], { stdio: "pipe" });
  } catch { /* the neutral scheme is the honest fallback */ }
}
if (existsSync(resolve("artifacts/brand-tokens.json"))) {
  brand = await read("artifacts/brand-tokens.json");
}

/** "2026-09-24","2026-09-26" -> "September 24 to 26, 2026" — a reader's date, not a log's. */
function humanDates(startIso, endIso) {
  if (!startIso) return null;
  const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  const [sy, sm, sd] = String(startIso).split("-").map(Number);
  const [ey, em, ed] = String(endIso ?? startIso).split("-").map(Number);
  if (sy === ey && sm === em) return `${months[sm - 1]} ${sd} to ${ed}, ${sy}`;
  return `${months[sm - 1]} ${sd} to ${months[em - 1]} ${ed}, ${ey}`;
}
const f = (name) => dossier.required_fields?.[name]?.value ?? null;

// ---- gate 1: compliance ----------------------------------------------------
if (String(dossier.gates?.draft_gate ?? "").startsWith("blocked")) {
  console.error(`Refusing to draft: ${dossier.company} is ${dossier.gates.draft_gate}.`);
  console.error(`  ${dossier.gates.draft_gate_reason}`);
  console.error(`  The gate clears when the client answers the question it names; then re-run.`);
  process.exit(4);
}

// ---- gate 2: a dated reason ------------------------------------------------
const reason = dossier.outreach?.reason_to_engage ?? null;
const reasonUrl = dossier.outreach?.reason_source_url ?? null;
if (reason && !reasonUrl) {
  console.error("Refusing to draft: reason_to_engage has no reason_source_url.");
  console.error("  A claim about the recipient's own activity carries the page it came from.");
  process.exit(4);
}
if (dossier.required_fields?.activation_history?.state !== "retrieved") {
  console.error("Refusing to draft: activation_history is not retrieved.");
  console.error(`  ${dossier.required_fields?.activation_history?.reason ?? "No dated activation signal."}`);
  console.error("  Read an activation page first: npm run signal -- --url <page>");
  process.exit(4);
}

// ---- props -----------------------------------------------------------------
// A greeting name comes only from a retrieved profile. Without one the draft opens to
// the company's sponsorship desk — honest and sendable, where an invented first name is
// neither. Supplying an exact LinkedIn URL in step 2 is what personalises this line.
const dm = dossier.required_fields?.decision_maker;
const firstName = dm?.state === "retrieved" ? String(dm.value ?? "").split(" ")[0] || null : null;
const greetingName = firstName ?? `${dossier.company} team`;

// The highlighted tier must be the deck's own. Anything else is dropped, because
// availability was never supplied and the sheet may state the rate card and no more.
const rateCard = festival.packages?.rate_card ?? [];
const named = dossier.outreach?.package_named ?? null;
const highlightTier = named && rateCard.some((t) => named.toLowerCase().includes(t.tier.toLowerCase()))
  ? rateCard.find((t) => named.toLowerCase().includes(t.tier.toLowerCase())).tier
  : null;

const props = {
  greetingName,
  companyName: dossier.company ?? null,
  // The personal note is authored in step 4, in the sender's register; the dated
  // reason is its floor, not its ceiling.
  personalNote: dossier.outreach?.personal_note ?? reason,
  reasonSourceUrl: reasonUrl ?? undefined,
  festivalName: festival.event_name ?? null,
  festivalDates: humanDates(festival.dates?.start, festival.dates?.end),
  festivalVenue: festival.venue?.name ?? null,
  festivalMarket: festival.venue?.market ?? null,
  distanceNote: festival.venue?.distance_note ?? null,
  stages: festival.format?.stages ?? [],
  audienceLine: festival.audience
    ? `Primary audience ${festival.audience.primary_age}, ${festival.audience.region}, household income ${festival.audience.household_income}.`
    : null,
  offerSheet: rateCard,
  highlightTier,
  heroImageUrl: dossier.outreach?.hero_image_url ?? undefined,
  callUrl: agencySender.calendly ?? null,
  senderName: agencySender.name ?? null,
  senderCompany: agencySender.company ?? null,
  optOutUrl: dossier.outreach?.opt_out_url ?? "",
  previewText: dossier.outreach?.preview_text ?? null,
  brand,
};

const missing = ["companyName", "festivalName", "personalNote", "callUrl", "previewText"]
  .filter((k) => !props[k]);
if (!dossier.outreach?.subject) missing.push("subject");
console.log(brand
  ? `brand: ${brand.source?.file ?? brand.source?.kind ?? "tokens"} · accent ${brand.palette?.accent ?? "—"} · display ${brand.type?.display ?? "—"}`
  : "brand: neutral default (no campaign tokens; run npm run brand)");
console.log(firstName
  ? `greeting: ${firstName} (retrieved decision maker)`
  : `greeting: ${greetingName} — a name renders only from a retrieved profile; supply an exact LinkedIn URL in step 2 to personalise`);
if (missing.length) {
  console.error(`Cannot render: ${missing.join(", ")} not populated. Write them in the step 5 judgement pass.`);
  process.exit(2);
}

// Zero-build: the template is pure-ESM createElement, so node renders it directly.
// A fresh clone has no node_modules, and the one thing that must never happen here is
// an operator working around a missing package by hand-writing the email. The template
// IS the deliverable: it carries the campaign's brand tokens, the rate card, the single
// ask, and the signature, and a typed-out text file carries none of them. So install
// once, retry, and if that fails say plainly that hand-writing is not the fallback.
async function loadRenderer() {
  const render = (await import("@react-email/render")).render;
  const SponsorPitch = (await import(new URL("../references/templates/sponsor-pitch.mjs", import.meta.url))).default;
  return { render, SponsorPitch };
}

let render, SponsorPitch;
try {
  ({ render, SponsorPitch } = await loadRenderer());
} catch {
  console.log("render dependencies absent, installing once…");
  try {
    execFileSync("npm", ["install", "--no-audit", "--no-fund", "--silent"], {
      cwd: resolve(import.meta.dirname, ".."), stdio: "pipe",
    });
    ({ render, SponsorPitch } = await loadRenderer());
    console.log("render dependencies installed");
  } catch (err) {
    console.error(`Cannot render: ${err.message}`);
    console.error("  Run `npm install` in the repo root, then re-run.");
    console.error("  Do not hand-write the email. The template carries the campaign's");
    console.error("  brand, the rate card, the single ask, and the signature; a typed");
    console.error("  text file carries none of them and is not this workflow's output.");
    process.exit(3);
  }
}

await mkdir(resolve("artifacts"), { recursive: true });
const el = SponsorPitch(props);
const html = await render(el);
const text = await render(el, { plainText: true });
await writeFile(resolve("artifacts/pitch.html"), html);
await writeFile(resolve("artifacts/pitch.txt"), text);
await writeFile(resolve("artifacts/pitch.props.json"),
  JSON.stringify({ props: { ...props, brand: undefined }, brand_source: brand?.source ?? "neutral_default",
                   subject: dossier.outreach?.subject ?? null,
                   review_state: "not_required",
                   send_state: "ready_to_send",
                   sender_authority: agencySender.authority_state ?? "authorized",
                   attendance_omitted: festival.attendance?.state === "disputed" }, null, 2) + "\n");

// The draft is part of the run's record: write the paths into the dossier and derive
// the packet again, so validate and the dashboard see what was actually produced.
const dossierPath = resolve(arg("dossier", "artifacts/dossier.json"));
const updated = JSON.parse(await readFile(dossierPath, "utf8"));
updated.outreach = { ...updated.outreach,
  draft_html_path: "artifacts/pitch.html",
  draft_text_path: "artifacts/pitch.txt",
  review_state: "not_required",
  send_state: "ready_to_send",
  sender_authority: agencySender.authority_state ?? "authorized",
};
await writeFile(dossierPath, JSON.stringify(updated, null, 2) + "\n");
// deliver.mjs re-assembles once after this step, so a nested assemble here would be
// the third build of the same packet in one run. Standalone, this still self-heals.
if (process.env.ORCHESTRATED === "1") {
  console.log("draft paths written to the dossier; deliver will attach them");
} else {
  try {
    execFileSync("node", [resolve(import.meta.dirname, "assemble.mjs")], { stdio: "pipe" });
    console.log("packet refreshed: draft attached to sponsors[0] and messages[]");
  } catch (err) {
    console.error(`packet refresh failed: ${err.message} — run npm run assemble by hand`);
  }
}

console.log(`artifacts/pitch.html  ${html.length} bytes`);
console.log(`artifacts/pitch.txt   ${text.length} bytes`);
console.log(`subject: ${dossier.outreach?.subject ?? "(unset)"}`);
console.log("review_state: not_required · send_state: ready_to_send");
if (festival.attendance?.state === "disputed") {
  console.log("attendance: omitted — the two client figures do not reconcile");
}
console.log(highlightTier
  ? `offer sheet: full rate card, ${highlightTier} highlighted`
  : "offer sheet: full rate card, no tier highlighted");
